name: "v2.4"

on:
  schedule:
    - cron: '0 4 * * 3'
  workflow_dispatch: 

env:
  # The default repo env will be 'ComputeStacks'; uppercase is not allowed.
  GH_REPO: computestacks/cs-docker-xtrabackup

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Github Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: 2.4/
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.GH_REPO }}:2.4
          cache-from: type=gha
          cache-to: type=gha,mode=max
